databases:
  - name: expense-tracker-db
    region: frankfurt
    plan: free
    databaseName: expense_tracker
    user: expense_tracker_user

services:
  - type: web
    region: frankfurt
    plan: free
    name: expense-tracker
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: expense-tracker-db
          property: connectionString
      - key: SECRET_KEY_DJANGO
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
